minerl:
  env_id: MineRLObtainDiamond-v0
  env_time_limit: 36000
  generator_prefill_steps: 100_000
  action_dim: 38
  generator_workers: 8
  gamma: 0.995
  adam_lr: 2.0e-4
  reset_interval: 200
  clip_rewards: log1p
  vecobs_weight: 10.0
  reward_weight: 10.0
  stoch_dim: 96
  kl_weight: 0.3
  entropy: 0.010
  imag_horizon: 5
  data_workers: 2
  # fast mode
  batch_length: 64
  batch_size: 64
  log_interval: 100
  logbatch_interval: 20000
  save_interval: 2000
  eval_interval: 20000
  #model
  deter_dim: 8192
  stoch_dim: 32
  stoch_discrete: 32
  hidden_dim: 1024
  gru_layers: 8
  gru_type: gru
  layer_norm: True
  vecobs_size: 0
  image_encoder: cnn
  cnn_depth: 96
  image_encoder_layers: 0
  image_decoder: cnn
  image_decoder_layers: 0
  reward_input: False
  reward_decoder_layers: 4
  reward_decoder_categorical:
  terminal_decoder_layers: 4

