minerl:
  env_id: MineRLObtainDiamond-v0
  env_time_limit: 18000
  action_dim: 38
  #Good: 10 2 2 2 batched
  generator_workers: 12
  inference_workers: 1 #number of processess
  inference_batch_size: 4 #For batched inference
  inference_data_workers: 1 #For multiprocess inference
  inference_type: multiproc #single/multiproc/batched
  learner_workers: 7
  data_workers: 2
  policy_inference: remote

  gamma: 0.995
  adam_lr: 5.0e-6
  adam_lr_actor: 5.0e-6
  adam_lr_critic: 5.0e-6
  reset_interval: 150
  clip_rewards: log1p
  vecobs_weight: 10.0
  reward_weight: 50.0
  kl_weight: 0.3
  entropy: 0.010
  imag_horizon: 10
  # fast mode
  batch_length: 64
  batch_size: 8
  log_interval: 100
  logbatch_interval: 1000
  save_interval: 500
  eval_interval: 1000

  generator_prefill_steps: 3_000

  model: dreamer
  deter_dim: 8192
  stoch_dim: 32
  stoch_discrete: 64
  hidden_dim: 32768
  gru_layers: 16
  gru_type: gru
  layer_norm: True
  vecobs_size: 0
  image_encoder: cnn
  cnn_depth: 192
  image_encoder_layers: 0
  image_decoder: cnn
  image_decoder_layers: 0
  reward_input: False
  reward_decoder_layers: 4
  reward_decoder_categorical:
  terminal_decoder_layers: 4